export interface AyurvedaFood {
  name: string;
  shortBenefit: string;
  description: string;
  benefits: string[];
  howToConsume: string;
  dailyIntakeLimit: string;
  scientificNote?: string;
  category: string;
}

export interface AyurvedaCategory {
  id: string;
  title: string;
  description: string;
  gradient: string;
  iconBg: string;
  iconColor: string;
  foods: AyurvedaFood[];
}

export const stressReliefFoods: AyurvedaFood[] = [
  { name: "Ashwagandha", shortBenefit: "Adaptogenic herb that reduces cortisol", category: "Herb", description: "Ashwagandha (Withania somnifera) is one of the most important herbs in Ayurveda, used for over 3,000 years to relieve stress and boost energy.", benefits: ["Significantly reduces cortisol levels by up to 30%", "Improves resistance to stress and anxiety", "Enhances sleep quality and reduces insomnia", "Boosts brain function and memory", "May reduce blood sugar levels"], howToConsume: "Mix 1/2 tsp powder in warm milk before bed, or take as capsules.", dailyIntakeLimit: "300–600 mg of root extract per day. Do not exceed 1,000 mg.", scientificNote: "A 2012 study in the Indian Journal of Psychological Medicine found 300 mg twice daily reduced stress scores by 44%." },
  { name: "Chamomile", shortBenefit: "Calming properties for relaxation", category: "Herb/Tea", description: "Chamomile is a gentle, calming herb widely used as a tea to reduce anxiety and promote sleep.", benefits: ["Promotes relaxation and reduces anxiety", "Improves sleep quality", "Has anti-inflammatory properties", "Soothes digestive discomfort", "May reduce menstrual pain"], howToConsume: "Steep 1–2 tsp dried flowers in hot water for 5–10 minutes. Drink as tea.", dailyIntakeLimit: "1–4 cups of chamomile tea per day. Avoid if allergic to ragweed.", scientificNote: "A 2016 study in Phytomedicine showed chamomile significantly reduced generalized anxiety disorder symptoms." },
  { name: "Almonds", shortBenefit: "Rich in magnesium for stress relief", category: "Dry Fruit", description: "Almonds are nutrient-dense nuts packed with magnesium, vitamin E, and healthy fats that support mental health.", benefits: ["High magnesium content helps relax muscles and nerves", "Vitamin E protects brain cells from oxidative stress", "Healthy fats support brain function", "B vitamins help produce serotonin", "Stabilizes blood sugar to prevent mood swings"], howToConsume: "Soak 8–10 almonds overnight and eat in the morning for best absorption.", dailyIntakeLimit: "20–23 almonds (about 28g) per day. Excess may cause weight gain and digestive issues.", scientificNote: "Magnesium deficiency is linked to increased anxiety. Almonds provide 20% DV of magnesium per serving." },
  { name: "Dark Chocolate", shortBenefit: "Mood-boosting antioxidants", category: "Food", description: "Dark chocolate (70%+ cocoa) contains flavonoids and compounds that boost mood and reduce stress hormones.", benefits: ["Stimulates endorphin production for pleasure", "Contains serotonin to act as antidepressant", "Flavonoids improve blood flow to the brain", "Reduces cortisol and catecholamines", "Rich in magnesium for relaxation"], howToConsume: "Eat 1–2 small squares (20–30g) of 70%+ dark chocolate daily.", dailyIntakeLimit: "30–60g per day maximum. Higher amounts add excess calories and caffeine.", scientificNote: "A 2009 study in the Journal of Proteome Research showed eating 40g dark chocolate daily for 2 weeks reduced cortisol." },
  { name: "Turmeric Milk (Golden Milk)", shortBenefit: "Anti-inflammatory & calming", category: "Beverage", description: "Turmeric milk is a traditional Ayurvedic drink combining turmeric, warm milk, and spices for deep relaxation.", benefits: ["Curcumin reduces brain inflammation linked to anxiety", "Promotes deep, restful sleep", "Boosts serotonin and dopamine levels", "Supports immune function", "Anti-inflammatory effects on the entire body"], howToConsume: "Mix 1/2 tsp turmeric with warm milk, add a pinch of black pepper and honey.", dailyIntakeLimit: "1–2 cups per day. Turmeric intake should not exceed 1,500 mg/day.", scientificNote: "Curcumin has been shown to increase BDNF levels, which helps with depression and anxiety." },
  { name: "Brahmi", shortBenefit: "Enhances mental clarity", category: "Herb", description: "Brahmi (Bacopa monnieri) is a powerful Ayurvedic herb known for enhancing cognitive function and reducing anxiety.", benefits: ["Reduces anxiety and mental fatigue", "Improves memory and concentration", "Contains bacosides that repair damaged neurons", "Acts as an adaptogen against stress", "Supports healthy neurotransmitter function"], howToConsume: "Take 300 mg standardized extract daily, or brew as tea.", dailyIntakeLimit: "300–450 mg of extract per day. May cause nausea in high doses.", scientificNote: "A 2014 meta-analysis confirmed Bacopa monnieri improves attention, cognitive processing, and working memory." },
  { name: "Walnuts", shortBenefit: "Omega-3 rich brain food", category: "Dry Fruit", description: "Walnuts are one of the best plant sources of omega-3 fatty acids, crucial for brain health and stress management.", benefits: ["Alpha-linolenic acid (ALA) reduces inflammation in the brain", "Supports serotonin production", "Polyphenols reduce oxidative stress", "Improves mood and cognitive function", "Melatonin content aids better sleep"], howToConsume: "Eat 4–7 walnut halves daily as a snack or add to salads.", dailyIntakeLimit: "7–10 walnut halves (about 30g) per day. High calorie — excess may cause weight gain.", scientificNote: "A 2020 study in Nutrients showed walnut consumption was associated with lower depression scores." },
  { name: "Banana", shortBenefit: "Natural source of tryptophan", category: "Fruit", description: "Bananas contain tryptophan, vitamin B6, and potassium, making them a natural mood booster and stress reliever.", benefits: ["Tryptophan converts to serotonin for mood elevation", "Vitamin B6 aids neurotransmitter production", "Potassium helps regulate blood pressure during stress", "Natural sugars provide quick energy without crashes", "Magnesium relaxes muscles"], howToConsume: "Eat 1–2 ripe bananas daily, ideally as a snack or smoothie.", dailyIntakeLimit: "1–2 bananas per day. Excess potassium can be harmful for kidney patients.", scientificNote: "Bananas provide about 10% DV of potassium and 25% DV of vitamin B6 per serving." },
  { name: "Lavender Tea", shortBenefit: "Aromatherapy in a cup", category: "Beverage", description: "Lavender has powerful calming properties used both as aromatherapy and consumed as tea for anxiety relief.", benefits: ["Reduces anxiety and restlessness", "Promotes deep sleep", "Lowers heart rate and blood pressure", "Relieves headaches caused by tension", "Soothes nervous system"], howToConsume: "Steep 1–2 tsp dried lavender buds in hot water for 5 minutes.", dailyIntakeLimit: "1–3 cups per day. Avoid during pregnancy.", scientificNote: "A 2012 study found lavender aromatherapy reduced anxiety in ICU patients by 36%." },
  { name: "Pumpkin Seeds", shortBenefit: "Zinc & magnesium powerhouse", category: "Seed", description: "Pumpkin seeds are rich in zinc, magnesium, and tryptophan — three nutrients directly linked to stress reduction.", benefits: ["Zinc deficiency is linked to mood disorders", "Magnesium promotes calmness", "Tryptophan converts to serotonin", "Iron content fights fatigue", "Antioxidants protect brain cells"], howToConsume: "Eat 1–2 tablespoons of raw or roasted seeds daily.", dailyIntakeLimit: "30g (about 2 tablespoons) per day. Excess may cause digestive discomfort.", scientificNote: "Just 28g of pumpkin seeds provides 37% DV of magnesium." },
  { name: "Jatamansi", shortBenefit: "Ayurvedic calming root", category: "Herb", description: "Jatamansi (Nardostachys jatamansi) is a revered Ayurvedic herb used for centuries to calm the mind and treat insomnia.", benefits: ["Stabilizes mood and reduces nervousness", "Promotes deep, restful sleep", "Balances neurotransmitter levels", "Reduces mental fatigue", "Has neuroprotective properties"], howToConsume: "Take 250–500 mg of root powder with warm water or milk before bed.", dailyIntakeLimit: "500 mg per day maximum. Consult a practitioner for long-term use.", scientificNote: "Studies show Jatamansi has GABA-enhancing effects similar to some anti-anxiety medications." },
  { name: "Saffron", shortBenefit: "Precious mood-enhancing spice", category: "Spice", description: "Saffron is one of the world's most precious spices with proven antidepressant and anti-anxiety properties.", benefits: ["Contains crocin and safranal with antidepressant effects", "Enhances serotonin metabolism", "Reduces PMS-related mood swings", "Has strong antioxidant properties", "Improves sleep quality"], howToConsume: "Add 2–3 strands to warm milk or rice dishes.", dailyIntakeLimit: "30 mg per day. Doses above 5g can be toxic.", scientificNote: "Multiple clinical trials show 30 mg saffron daily is as effective as fluoxetine for mild-to-moderate depression." },
];

export const bloodPressureFoods: AyurvedaFood[] = [
  { name: "Garlic", shortBenefit: "Natural blood pressure regulator", category: "Spice/Herb", description: "Garlic contains allicin, a compound that helps relax blood vessels and reduce blood pressure naturally.", benefits: ["Allicin widens blood vessels", "Reduces both systolic and diastolic pressure by 8–10 mmHg", "Thins blood and improves circulation", "Lowers cholesterol levels", "Has antibacterial and antiviral properties"], howToConsume: "Eat 1–2 raw crushed garlic cloves on empty stomach, or add generously to cooking.", dailyIntakeLimit: "2–5g fresh garlic (1–2 cloves) per day. Excess may cause digestive issues and blood thinning.", scientificNote: "A 2008 meta-analysis in BMC Cardiovascular Disorders found garlic reduced systolic BP by an average of 8.4 mmHg." },
  { name: "Pomegranate", shortBenefit: "Improves blood flow", category: "Fruit", description: "Pomegranate is a powerful fruit rich in antioxidants that improve cardiovascular health and blood flow.", benefits: ["Potent antioxidants reduce arterial plaque", "Improves blood flow to the heart", "Reduces systolic blood pressure", "Lowers LDL cholesterol oxidation", "Anti-inflammatory effects on blood vessels"], howToConsume: "Drink 1 cup (240ml) fresh pomegranate juice daily or eat the whole fruit.", dailyIntakeLimit: "1 cup juice or 1 whole fruit per day. May interact with blood pressure medications.", scientificNote: "A 2017 meta-analysis showed pomegranate juice reduced systolic BP by 5 mmHg on average." },
  { name: "Spinach", shortBenefit: "High in potassium & nitrates", category: "Leafy Green", description: "Spinach is loaded with potassium, nitrates, and magnesium — all essential minerals for blood pressure regulation.", benefits: ["High potassium helps the body excrete excess sodium", "Nitrates relax blood vessels", "Magnesium supports healthy blood pressure", "Rich in folate for heart health", "Low calorie and nutrient-dense"], howToConsume: "Eat 1–2 cups raw in salads or 1/2 cup cooked daily.", dailyIntakeLimit: "2–3 cups raw or 1 cup cooked per day. Those on blood thinners should maintain consistent intake (vitamin K).", scientificNote: "Dietary nitrates from leafy greens can reduce BP by 4–10 mmHg within hours." },
  { name: "Beetroot", shortBenefit: "Natural nitric oxide booster", category: "Root Vegetable", description: "Beetroot is one of the best natural sources of dietary nitrates, which convert to nitric oxide to relax blood vessels.", benefits: ["Dramatically increases nitric oxide levels", "Can lower blood pressure within 3–6 hours", "Improves exercise endurance", "Rich in antioxidants (betalains)", "Supports liver detoxification"], howToConsume: "Drink 250ml fresh beetroot juice daily or eat roasted beets.", dailyIntakeLimit: "1–2 beets or 250ml juice per day. May cause red urine (harmless). Avoid with kidney stones (oxalates).", scientificNote: "A 2013 study showed 250ml beetroot juice lowered systolic BP by 4–5 mmHg in 6 hours." },
  { name: "Hibiscus Tea", shortBenefit: "Lowers systolic pressure", category: "Beverage", description: "Hibiscus tea is made from dried hibiscus flowers and has been scientifically shown to lower blood pressure.", benefits: ["Acts as a natural ACE inhibitor", "Reduces systolic pressure by 7–11 mmHg", "Rich in vitamin C and antioxidants", "Has mild diuretic effect", "Supports healthy cholesterol levels"], howToConsume: "Steep 1–2 tsp dried hibiscus in hot water for 5–10 minutes. Drink warm or cold.", dailyIntakeLimit: "2–3 cups per day. May interact with blood pressure and diabetes medications.", scientificNote: "A 2010 study in the Journal of Nutrition found 3 cups daily lowered systolic BP by 7 mmHg in 6 weeks." },
  { name: "Arjuna Bark", shortBenefit: "Traditional cardiac tonic", category: "Herb", description: "Arjuna (Terminalia arjuna) bark is one of the most important Ayurvedic heart tonics, used for centuries for cardiovascular health.", benefits: ["Strengthens heart muscle", "Reduces blood pressure naturally", "Improves coronary blood flow", "Has anti-atherogenic properties", "Reduces chest pain (angina)"], howToConsume: "Boil 1/2 tsp bark powder in milk for 5 min. Drink once daily.", dailyIntakeLimit: "500 mg–1g bark powder per day. Consult a doctor if on heart medications.", scientificNote: "Studies show Arjuna bark improves left ventricular ejection fraction in heart failure patients." },
  { name: "Banana", shortBenefit: "Potassium-rich fruit", category: "Fruit", description: "Bananas are one of the best dietary sources of potassium, which is critical for blood pressure regulation.", benefits: ["High potassium counters sodium effects", "Helps kidneys excrete excess sodium", "Relaxes blood vessel walls", "Provides quick natural energy", "Contains magnesium for heart health"], howToConsume: "Eat 1–2 bananas daily as a snack.", dailyIntakeLimit: "2–3 bananas per day. Those with kidney disease should limit potassium intake.", scientificNote: "Adults consuming 4,700 mg of potassium daily had a 25% lower risk of high blood pressure." },
  { name: "Flaxseeds", shortBenefit: "Omega-3 for heart health", category: "Seed", description: "Flaxseeds are rich in alpha-linolenic acid (ALA), lignans, and fiber — all beneficial for cardiovascular health.", benefits: ["ALA omega-3 reduces inflammation in arteries", "Lignans have antihypertensive effects", "Fiber helps reduce cholesterol", "Reduces arterial stiffness", "Supports healthy endothelial function"], howToConsume: "Grind 1–2 tablespoons and add to smoothies, yogurt, or oatmeal.", dailyIntakeLimit: "2 tablespoons (20g) ground flaxseed per day. Must be ground for absorption.", scientificNote: "A 2013 study in Hypertension found 30g ground flax daily reduced systolic BP by 10 mmHg in 6 months." },
  { name: "Watermelon", shortBenefit: "L-citrulline for vessel relaxation", category: "Fruit", description: "Watermelon contains L-citrulline, which the body converts to L-arginine, producing nitric oxide to relax blood vessels.", benefits: ["L-citrulline improves blood vessel flexibility", "Natural diuretic reduces fluid retention", "Lycopene protects heart health", "Low calorie and hydrating", "Rich in potassium and magnesium"], howToConsume: "Eat 2 cups of fresh watermelon daily.", dailyIntakeLimit: "2–3 cups per day. High in natural sugars — diabetics should moderate intake.", scientificNote: "Florida State University research showed watermelon extract reduced aortic blood pressure in adults with prehypertension." },
  { name: "Celery", shortBenefit: "Phthalides relax arteries", category: "Vegetable", description: "Celery contains phthalides, compounds that relax the tissues of artery walls and increase blood flow.", benefits: ["Phthalides reduce stress hormones that constrict vessels", "Natural diuretic effect", "Anti-inflammatory properties", "Rich in potassium and folate", "Very low calorie"], howToConsume: "Eat 4 stalks of celery daily or drink fresh celery juice.", dailyIntakeLimit: "4–6 stalks per day. Those on blood thinners should consult their doctor.", scientificNote: "Traditional Chinese Medicine has used celery for hypertension for centuries; modern studies confirm phthalide compounds lower BP." },
  { name: "Yogurt (Dahi)", shortBenefit: "Probiotics for heart health", category: "Dairy", description: "Yogurt is rich in probiotics, calcium, and potassium — nutrients that support cardiovascular health and blood pressure.", benefits: ["Probiotics improve gut-heart axis", "Calcium supports blood vessel contraction/relaxation", "Potassium balances sodium", "Peptides act as natural ACE inhibitors", "Protein promotes satiety"], howToConsume: "Eat 1 cup of plain unsweetened yogurt daily with meals.", dailyIntakeLimit: "1–2 cups per day. Choose low-fat or plain varieties.", scientificNote: "A 2021 study in the American Journal of Hypertension linked daily yogurt consumption to 7% lower BP risk." },
  { name: "Dark Chocolate", shortBenefit: "Flavonoids improve vessel function", category: "Food", description: "Dark chocolate (70%+) contains flavanols that stimulate nitric oxide production, improving blood vessel function.", benefits: ["Flavanols increase nitric oxide production", "Improves endothelial function", "Reduces arterial stiffness", "Lowers blood pressure by 2–3 mmHg", "Rich in magnesium"], howToConsume: "Eat 1–2 squares (20–30g) of 70%+ dark chocolate daily.", dailyIntakeLimit: "30g per day. Higher cocoa percentage is better.", scientificNote: "A Cochrane review of 35 studies confirmed cocoa-rich foods reduce blood pressure." },
];

export const bloodSugarFoods: AyurvedaFood[] = [
  { name: "Bitter Gourd (Karela)", shortBenefit: "Natural insulin-like compounds", category: "Vegetable", description: "Bitter gourd contains charantin, vicine, and polypeptide-p, which mimic insulin and help lower blood sugar.", benefits: ["Contains insulin-like compounds (polypeptide-p)", "Charantin helps glucose uptake in cells", "Reduces HbA1c levels", "Improves glucose tolerance", "Supports pancreatic beta cell function"], howToConsume: "Drink 30ml fresh bitter gourd juice on empty stomach, or eat cooked in meals.", dailyIntakeLimit: "50–100ml juice or 1 medium bitter gourd per day. Excess can cause abdominal pain and diarrhea.", scientificNote: "A 2011 study in the Journal of Ethnopharmacology showed bitter gourd reduced fasting blood glucose by 15–20%." },
  { name: "Fenugreek (Methi)", shortBenefit: "Improves glucose tolerance", category: "Seed/Spice", description: "Fenugreek seeds contain soluble fiber and 4-hydroxyisoleucine, which help slow carbohydrate absorption and improve insulin action.", benefits: ["Soluble fiber slows sugar absorption", "4-hydroxyisoleucine stimulates insulin secretion", "Reduces fasting blood glucose", "Lowers HbA1c by 1–2%", "Improves lipid profile"], howToConsume: "Soak 1–2 tsp seeds overnight in water and drink in the morning, or add to cooking.", dailyIntakeLimit: "5–30g seeds per day (start low). May cause digestive bloating initially.", scientificNote: "A meta-analysis of 10 trials showed fenugreek reduced fasting blood glucose by 17.6 mg/dL on average." },
  { name: "Cinnamon (Dalchini)", shortBenefit: "Enhances insulin sensitivity", category: "Spice", description: "Cinnamon contains cinnamaldehyde and type-A procyanidins that improve insulin sensitivity and glucose metabolism.", benefits: ["Improves insulin receptor sensitivity", "Reduces fasting blood sugar by 10–29%", "Slows carbohydrate breakdown in gut", "Has anti-inflammatory properties", "Mimics insulin activity"], howToConsume: "Add 1/2–1 tsp cinnamon powder to tea, oatmeal, or warm water daily.", dailyIntakeLimit: "1–6g (up to 1 tsp) per day. Use Ceylon cinnamon to avoid coumarin toxicity.", scientificNote: "A 2003 study in Diabetes Care showed 1–6g cinnamon daily reduced fasting glucose by 18–29% in type 2 diabetics." },
  { name: "Jamun (Indian Blackberry)", shortBenefit: "Converts starch to energy", category: "Fruit", description: "Jamun is a traditional Ayurvedic fruit whose seeds contain jamboline, which controls the conversion of starch into sugar.", benefits: ["Jamboline regulates starch-to-sugar conversion", "Seeds reduce blood sugar levels", "Astringent properties help pancreatic function", "Low glycemic index fruit", "Rich in antioxidants"], howToConsume: "Eat 100g fresh fruit in season. Dry and powder seeds for year-round use.", dailyIntakeLimit: "100–200g fruit or 3–5g seed powder per day. Avoid on empty stomach.", scientificNote: "Studies show Jamun seed extract reduced blood glucose by 30% in diabetic animal models." },
  { name: "Amla (Indian Gooseberry)", shortBenefit: "Rich in chromium for metabolism", category: "Fruit", description: "Amla is extremely rich in vitamin C and chromium, which help regulate carbohydrate metabolism and insulin response.", benefits: ["Chromium enhances insulin signaling", "Vitamin C protects pancreatic cells", "Reduces post-meal blood sugar spikes", "Improves lipid profile in diabetics", "Powerful antioxidant protection"], howToConsume: "Eat 1–2 fresh amla daily, or take 1 tsp amla powder with water.", dailyIntakeLimit: "1–2 fresh fruits or 3–6g powder per day. Excess may cause acid reflux.", scientificNote: "A 2011 study showed 3g amla powder daily reduced fasting and post-meal blood sugar significantly." },
  { name: "Neem", shortBenefit: "Reduces blood sugar levels", category: "Herb", description: "Neem leaves have hypoglycemic properties and are used in Ayurveda to manage diabetes and purify blood.", benefits: ["Flavonoids reduce blood glucose levels", "Improves insulin receptor sensitivity", "Helps in glycogenesis", "Purifies blood and improves circulation", "Anti-inflammatory and antimicrobial"], howToConsume: "Chew 4–5 tender neem leaves on empty stomach, or take neem extract capsules.", dailyIntakeLimit: "4–5 leaves or 250–500 mg extract per day. Not recommended during pregnancy.", scientificNote: "Research published in the Indian Journal of Pharmacology confirmed neem leaf extract has significant antidiabetic activity." },
  { name: "Turmeric (Haldi)", shortBenefit: "Curcumin prevents insulin resistance", category: "Spice", description: "Turmeric's active compound curcumin has been shown to prevent and reverse insulin resistance and improve beta-cell function.", benefits: ["Curcumin reduces insulin resistance", "Lowers blood sugar levels", "Protects pancreatic beta cells", "Anti-inflammatory effects reduce diabetic complications", "Prevents progression from prediabetes to diabetes"], howToConsume: "Use 1/2 tsp in cooking daily or take with warm milk and black pepper.", dailyIntakeLimit: "500–2,000 mg curcumin per day. Always consume with black pepper for absorption.", scientificNote: "A 2012 Thai study showed curcumin supplementation prevented 100% of prediabetic patients from developing type 2 diabetes over 9 months." },
  { name: "Aloe Vera", shortBenefit: "Improves fasting blood glucose", category: "Plant", description: "Aloe vera gel contains compounds that enhance insulin secretion and improve glucose utilization by cells.", benefits: ["Reduces fasting blood glucose", "Improves HbA1c levels", "Phytosterols have anti-hyperglycemic effects", "Supports digestive health", "Anti-inflammatory for diabetic complications"], howToConsume: "Drink 1–2 tablespoons of fresh aloe vera gel juice on empty stomach.", dailyIntakeLimit: "30–50ml juice per day. Excess can cause laxative effects.", scientificNote: "A meta-analysis of 9 studies showed aloe vera reduced fasting blood glucose by 30.05 mg/dL and HbA1c by 0.41%." },
  { name: "Drumstick (Moringa Leaves)", shortBenefit: "Isothiocyanates regulate blood sugar", category: "Vegetable/Herb", description: "Moringa leaves contain isothiocyanates that help regulate blood sugar and are packed with nutrients.", benefits: ["Isothiocyanates reduce blood sugar spikes", "Rich in chlorogenic acid which regulates glucose", "Provides complete nutrition with all amino acids", "Anti-inflammatory properties", "Supports healthy insulin production"], howToConsume: "Add fresh leaves to dal/soup or take 1/2 tsp moringa powder daily.", dailyIntakeLimit: "1–2 tsp leaf powder or a handful of fresh leaves per day.", scientificNote: "A study in the Journal of Food Science showed moringa leaf powder reduced post-meal blood sugar by 21%." },
  { name: "Flaxseeds (Alsi)", shortBenefit: "Fiber slows sugar absorption", category: "Seed", description: "Flaxseeds are rich in soluble fiber and lignans that slow down sugar absorption and improve insulin sensitivity.", benefits: ["Soluble fiber slows glucose absorption", "Lignans improve insulin sensitivity", "Omega-3 ALA reduces inflammation", "Improves gut microbiome for better metabolism", "Reduces cardiovascular risk in diabetics"], howToConsume: "Grind 1–2 tablespoons and add to yogurt, smoothies, or rotis.", dailyIntakeLimit: "2 tablespoons (20g) ground per day. Must be ground for benefits.", scientificNote: "A 2018 study showed 10g ground flaxseed daily for 12 weeks reduced fasting blood sugar by 19.7%." },
  { name: "Green Tea", shortBenefit: "Catechins improve insulin function", category: "Beverage", description: "Green tea contains EGCG and other catechins that improve insulin sensitivity and reduce blood sugar levels.", benefits: ["EGCG improves insulin sensitivity", "Reduces fasting blood sugar", "Catechins inhibit carbohydrate digestion", "Reduces risk of type 2 diabetes by 18%", "Antioxidants protect pancreatic cells"], howToConsume: "Steep 1 tsp leaves in hot (not boiling) water for 2–3 minutes. Drink without sugar.", dailyIntakeLimit: "3–4 cups per day. Avoid on empty stomach. Caffeine sensitive individuals should limit intake.", scientificNote: "A Japanese study of 17,413 adults showed those drinking 6+ cups of green tea daily had 33% lower type 2 diabetes risk." },
  { name: "Barley (Jau)", shortBenefit: "Low glycemic whole grain", category: "Grain", description: "Barley has one of the lowest glycemic indices among grains and is rich in beta-glucan fiber.", benefits: ["Very low glycemic index (28)", "Beta-glucan fiber slows sugar absorption", "Improves insulin sensitivity", "Reduces post-meal blood sugar spikes by 59–65%", "Promotes beneficial gut bacteria"], howToConsume: "Replace rice with barley in meals, or drink barley water.", dailyIntakeLimit: "1–2 servings per day. Not suitable for those with celiac disease (contains gluten).", scientificNote: "A study showed eating barley-based bread reduced blood sugar response by 59–65% compared to white bread." },
];

export const antiSwellingFoods: AyurvedaFood[] = [
  { name: "Turmeric (Haldi)", shortBenefit: "Powerful curcumin compound", category: "Spice", description: "Turmeric contains curcumin, one of the most powerful natural anti-inflammatory compounds known to science.", benefits: ["Curcumin blocks NF-κB inflammatory pathway", "As effective as some anti-inflammatory drugs", "Reduces joint pain and swelling", "Protects against chronic inflammation-related diseases", "Powerful antioxidant that neutralizes free radicals"], howToConsume: "Use 1/2–1 tsp in cooking daily with black pepper and fat for absorption.", dailyIntakeLimit: "500–2,000 mg curcumin per day. Always pair with black pepper (piperine increases absorption by 2,000%).", scientificNote: "A 2014 study in the Journal of Medicinal Food found curcumin as effective as ibuprofen for knee osteoarthritis pain." },
  { name: "Ginger (Adrak)", shortBenefit: "Gingerols reduce inflammation", category: "Root/Spice", description: "Ginger contains gingerols and shogaols, bioactive compounds with powerful anti-inflammatory and antioxidant effects.", benefits: ["Gingerols inhibit pro-inflammatory cytokines", "Reduces muscle soreness by 25%", "Relieves nausea and digestive inflammation", "Helps with osteoarthritis symptoms", "Improves circulation and reduces swelling"], howToConsume: "Add fresh ginger to tea, food, or chew a small piece daily.", dailyIntakeLimit: "1–3g fresh ginger per day. Excess may cause heartburn. Avoid large amounts if on blood thinners.", scientificNote: "A 2015 meta-analysis showed ginger supplementation significantly reduced CRP (C-reactive protein) levels." },
  { name: "Moringa", shortBenefit: "Rich in antioxidants", category: "Herb/Vegetable", description: "Moringa oleifera is called the 'miracle tree' — its leaves contain isothiocyanates and quercetin with strong anti-inflammatory properties.", benefits: ["Isothiocyanates reduce inflammation at cellular level", "Quercetin fights oxidative stress", "Contains 46 antioxidants", "Reduces arthritis-related inflammation", "7x more vitamin C than oranges"], howToConsume: "Add 1/2–1 tsp moringa powder to smoothies, soups, or warm water.", dailyIntakeLimit: "1–2 tsp (5–10g) leaf powder per day. Avoid root and bark (may be toxic in high doses).", scientificNote: "Lab studies show moringa leaf extract reduces inflammatory markers (TNF-α, IL-6) by over 50%." },
  { name: "Giloy (Guduchi)", shortBenefit: "Immune-boosting properties", category: "Herb", description: "Giloy (Tinospora cordifolia) is known as 'Amrita' (nectar of immortality) in Ayurveda for its anti-inflammatory and immune-modulating properties.", benefits: ["Modulates immune response to reduce chronic inflammation", "Rich in anti-inflammatory alkaloids", "Reduces fever and inflammation", "Protects liver from inflammatory damage", "Enhances macrophage function"], howToConsume: "Boil 1-inch stem in water or take 500mg giloy extract daily.", dailyIntakeLimit: "1–2g powder or 500mg extract per day. Avoid in autoimmune conditions without guidance.", scientificNote: "Research shows Giloy suppresses production of pro-inflammatory cytokines while enhancing anti-inflammatory ones." },
  { name: "Boswellia (Shallaki)", shortBenefit: "Traditional anti-inflammatory", category: "Herb/Resin", description: "Boswellia serrata produces a resin with boswellic acids that inhibit the 5-LOX enzyme, a key driver of inflammation.", benefits: ["Boswellic acids inhibit 5-lipoxygenase enzyme", "Reduces joint swelling and stiffness", "Improves mobility in arthritis patients", "Protects cartilage from degradation", "Works synergistically with curcumin"], howToConsume: "Take 300–500mg Boswellia extract capsules 2–3 times daily.", dailyIntakeLimit: "900–1,500mg extract per day. May cause mild digestive upset initially.", scientificNote: "A 2020 study showed Boswellia reduced knee pain by 50% and improved walking distance in osteoarthritis patients." },
  { name: "Holy Basil (Tulsi)", shortBenefit: "Adaptogenic & healing", category: "Herb", description: "Tulsi is a sacred herb in Ayurveda that contains eugenol, rosmarinic acid, and ursolic acid with powerful anti-inflammatory effects.", benefits: ["Eugenol blocks COX-2 enzyme (like aspirin)", "Reduces inflammatory markers in the body", "Adaptogenic — helps body handle stress-related inflammation", "Antibacterial and antiviral", "Protects organs from chemical stress"], howToConsume: "Chew 5–8 fresh leaves daily or drink tulsi tea 2–3 times a day.", dailyIntakeLimit: "5–10 leaves or 2–3 cups tulsi tea per day. May lower blood sugar — monitor if diabetic.", scientificNote: "Clinical studies show tulsi significantly reduces inflammatory markers CRP, IL-6, and TNF-α." },
  { name: "Omega-3 Fish Oil", shortBenefit: "EPA/DHA combat inflammation", category: "Supplement", description: "Omega-3 fatty acids (EPA and DHA) are among the most studied anti-inflammatory compounds, reducing systemic inflammation.", benefits: ["EPA and DHA produce anti-inflammatory resolvins", "Reduces joint stiffness and tenderness", "Lowers CRP and IL-6 levels", "Protects heart from inflammation", "Improves brain health and reduces neuroinflammation"], howToConsume: "Take 1–2 fish oil capsules daily with meals, or eat fatty fish 2–3 times per week.", dailyIntakeLimit: "1–3g combined EPA/DHA per day. Higher doses may increase bleeding risk.", scientificNote: "A 2017 meta-analysis of 68 studies confirmed omega-3 supplementation significantly reduces CRP, IL-6, and TNF-α." },
  { name: "Pineapple", shortBenefit: "Bromelain enzyme reduces swelling", category: "Fruit", description: "Pineapple contains bromelain, a group of enzymes that break down proteins and reduce inflammation and swelling.", benefits: ["Bromelain reduces post-surgical swelling", "Helps with sinusitis and nasal inflammation", "Aids digestion of inflammatory proteins", "Reduces muscle soreness after exercise", "Rich in vitamin C for immune support"], howToConsume: "Eat 1–2 cups of fresh pineapple or drink fresh juice. The core has the most bromelain.", dailyIntakeLimit: "1–2 cups per day. High in natural sugars — moderate for diabetics. May cause mouth irritation in excess.", scientificNote: "Bromelain has been shown to reduce nasal mucosal inflammation in sinusitis patients by 78%." },
  { name: "Cherries", shortBenefit: "Anthocyanins fight gout inflammation", category: "Fruit", description: "Cherries, especially tart cherries, contain anthocyanins that block inflammatory enzymes and reduce uric acid levels.", benefits: ["Anthocyanins inhibit COX-1 and COX-2 enzymes", "Reduces gout flare-ups by 35%", "Lowers uric acid levels", "Reduces muscle soreness post-exercise", "Improves sleep quality (natural melatonin)"], howToConsume: "Eat 1 cup of fresh cherries or drink 240ml tart cherry juice daily.", dailyIntakeLimit: "1–2 cups fresh or 240ml juice per day. High sugar content — watch with diabetes.", scientificNote: "A 2012 study showed cherry consumption reduced gout attacks by 35%. Combining with allopurinol reduced risk by 75%." },
  { name: "Extra Virgin Olive Oil", shortBenefit: "Oleocanthal mimics ibuprofen", category: "Oil", description: "Extra virgin olive oil contains oleocanthal, a compound with anti-inflammatory properties similar to ibuprofen.", benefits: ["Oleocanthal inhibits same pathways as ibuprofen", "Reduces risk of inflammatory diseases", "Polyphenols protect against oxidative stress", "Improves joint mobility", "Supports heart health"], howToConsume: "Use 2–3 tablespoons daily as salad dressing or drizzle on cooked food. Don't heat to smoke point.", dailyIntakeLimit: "2–4 tablespoons per day. High in calories (120 cal/tbsp) — factor into daily intake.", scientificNote: "Researchers found 50ml extra virgin olive oil has anti-inflammatory effect equivalent to 10% of an adult ibuprofen dose." },
  { name: "Triphala", shortBenefit: "Three-fruit anti-inflammatory formula", category: "Herb", description: "Triphala is an Ayurvedic formulation of three fruits (Amla, Haritaki, Bibhitaki) with powerful anti-inflammatory and antioxidant effects.", benefits: ["Gallic acid and ellagic acid reduce inflammation", "Balances all three doshas", "Improves gut health (gut inflammation is root of many diseases)", "Rich in vitamin C and antioxidants", "Supports detoxification"], howToConsume: "Mix 1/2 tsp powder in warm water and drink before bed or on empty stomach.", dailyIntakeLimit: "1–3g powder per day. May cause loose stools initially as it detoxifies.", scientificNote: "A 2017 study showed Triphala extract inhibited inflammatory cytokines comparable to prescription anti-inflammatory drugs." },
  { name: "Green Leafy Vegetables", shortBenefit: "Chlorophyll and antioxidants", category: "Vegetable", description: "Green leafy vegetables like kale, spinach, and collards are packed with anti-inflammatory vitamins, minerals, and phytonutrients.", benefits: ["Vitamin K reduces inflammatory markers", "Rich in alpha-linolenic acid (omega-3)", "Chlorophyll has anti-inflammatory properties", "Folate reduces homocysteine inflammation", "Fiber feeds anti-inflammatory gut bacteria"], howToConsume: "Eat 2–3 cups of mixed greens daily in salads, smoothies, or cooked.", dailyIntakeLimit: "2–4 cups per day. Those on warfarin should keep vitamin K intake consistent.", scientificNote: "Harvard research showed people eating 1+ servings of leafy greens daily had significantly lower inflammatory markers." },
];
